### ISSUE TITLE
Minions deleting oneblock's magic block

### ISSUE THREAD

**Issue by ZyXpe** [BentoBoxWorld/AOneBlock#132]
#### Describe the bug
I'm using JetsMinions plugin. This plugin supports to bentobox but i place minion in front of oneblock's magic block. Minions break magic block and block go disappear. Magic block not recharging use minion.

#### Screenshots and videos (Optional)

https://prnt.sc/w9nle9

##### Output of `/bbox version` (Mandatory)

```
https://prnt.sc/w9nm2o
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
I don't think this can be solved unless the minions plugin fires an event. However, try changing `drop-on-top` to false in AOneBlock's config.yml, then restart:

```
island:
  # Drop broken blocks on top of magic block
  # If you want Jobs or other plugins to recognize magic block breaking this must be false
  # Added since 1.3.0.
  drop-on-top: false
```

I don't think it will make any difference though.

**Comment by Teyir** [comment]
Hey,

I have the same issue 

This is the video -> https://youtu.be/5iCZGnR9H8s

This is my bbox version -> 
![image](https://user-images.githubusercontent.com/60007549/108916250-4863b800-762e-11eb-887d-4f26e922a114.png)

I have test with `drop-on-top:` false & true but that change nothing 


Thank you very much

**Comment by tastybento** [comment]
The only way to do this from looking at other plugins that integrate with this plugin is to listen for the `me.jet315.minions.events.MinerBlockBreakEvent` which occurs when the minion breaks a block.

Problems:
1. It's a premium plugin.
2. There's no source code.
3. There's no Maven repo so our build tools will not build it unless the plugin jar is available, which it can't be because it's not open source (see 1).

One plugin gets around 3 by having a private password-protected private libs repo, which would make it possible for us to build the code, but not others. So, we're hitting up against closed-source vs open-source philosophies here. Unless someone knows of a way to do this, or Jets makes an API with a Maven repo then I don't see how this is going to be possible, sorry.

**Comment by BONNe** [comment]
Tasty, you could use BlockPhysicUpadeEvent. It will detect that block is removed.

**Comment by Teyir** [comment]
I have contact the plugin developper for the integration

**Comment by tastybento** [comment]
Thanks for tip @BONNe and reaching out to the developer @Teyir. I'll try that event and that might work although I have no way to test it.

By the way, I'm not against premium plugins but if the developer would like integrations then a buildable API would be helpful.

**Comment by Teyir** [comment]
Ok thank you very much, if you want a tester I'm here

**Comment by tastybento** [comment]
The author reached out and changed his plugin to fire an EntityInteractEvent which I am able to listen for. However, I still need some changes so I can cancel the event because sometimes the block should not be broken.

**Comment by tastybento** [comment]
This is now fixed and tested with the latest version of JetsMinions v6.9.3.
