### ISSUE TITLE
Chests are empty in desolation phase

### ISSUE THREAD

**Issue by Koudyasek** [BentoBoxWorld/AOneBlock#133]
#### Describe the bug

Chests are empty in desolation phase

#### Steps to reproduce the behavior

https://pastebin.com/EQ48tED6

#### Expected behavior

https://pastebin.com/EQ48tED6

#### Screenshots and videos (Optional)

https://pastebin.com/EQ48tED6

##### Output of `/bbox version` (Mandatory)

```
https://prnt.sc/wg80dj
_______
```

#### Plugins (Optional)

```
---
_______
```
 
### Additional context (Optional)

desolation:  https://pastebin.com/AuAQZk6K

solving that on discord.

**Comment by EvilLord1323** [comment]
You can change chest at any phase in bentobox/addons/AOneBlock/phases

**Comment by Koudyasek** [comment]
I had fresh installed phases chests, and it still doesn't work

**Comment by tastybento** [comment]
This isn't a bug, the chests in desolation are supposed to mostly be empty, but there are 3 chest types. Two are Rare and one is Epic. As a result, they don't come up very often, and as there are no Normal chests, if the dice don't roll for Rare or Epic, the chest will be empty. That's because it's "Desolation". :-)

You can change the rarity if you like in the `9500_desolation_chests.yml` file. And here's a screenshot just to show they do come up...

<img width="376" alt="Screen Shot 2021-03-06 at 6 25 13 PM" src="https://user-images.githubusercontent.com/4407265/110227116-d6029b80-7ea9-11eb-865b-53db2c6d9762.png">
