### ISSUE TITLE
Changing oneblock island area.

### ISSUE THREAD

**Issue by Maftyyn** [BentoBoxWorld/AOneBlock#138]
#### Describe the solution you'd like us to implement.

Hey, is there any chance that i could make oneblock island bigger? For example players have 50x50 and i would like to make it bigger without reseting thems, so they dont lose they progress, i have 60ppl on server and that would be critical, also i want to make bigger island for future, because i did not expected such as 60 players and 50x50 isnt enough. So can i make it possible to expand it just for new players that they will have bigger, or if someone reset oneblock they will have new size too?

**Comment by tastybento** [comment]
You can change the protection range. For new players, just edit config.yml in your AOneBlock folder so that it's bigger:

```
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /bsbadmin range set <player> <new range>
  # or set this permission: aoneblock.island.range.<number>
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  protection-range: 50
```

You can increase it up to the "distance-between-islands" value. As it says too, you can set people's island range using an admin command, or give everyone a permission to increase it.
