### ISSUE TITLE
Hostile Mobs Won't Spawn Except On The One Block Block.

### ISSUE THREAD

**Issue by ZombieSkull** [BentoBoxWorld/AOneBlock#148]
#### Describe the bug

when trying to use spawn eggs or spawners for hostile mobs, nothing spawns.
#### Steps to reproduce the behavior

click hostile mob egg to ground, set hostile mob spawner on ground with no light but players near by,
#### Expected behavior

hostile mobs should spawn
##### Output of `/bbox version` (Mandatory)

```27.02 15:50:33 [Server] INFO Running PAPER Invalid.
27.02 15:50:33 [Server] INFO BentoBox version: 1.15.5
27.02 15:50:33 [Server] INFO Database: JSON
27.02 15:50:33 [Server] INFO Loaded Game Worlds:
27.02 15:50:33 [Server] INFO acidisland_world (AcidIsland): Overworld, Nether, The End
27.02 15:50:33 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
27.02 15:50:33 [Server] INFO caveblock-world (CaveBlock): Overworld, Nether, The End
27.02 15:50:33 [Server] INFO oneblock_world (OneBlock): Overworld, Nether
27.02 15:50:33 [Server] INFO skygrid-world (SkyGrid): Overworld, Nether, The End
27.02 15:50:33 [Server] INFO Loaded Addons:
27.02 15:50:33 [Server] INFO AcidIsland 1.14.6 (ENABLED)
27.02 15:50:33 [Server] INFO AOneBlock 1.5.1 (ENABLED)
27.02 15:50:33 [Server] INFO Bank 1.3.0 (ENABLED)
27.02 15:50:33 [Server] INFO Biomes 1.14.0 (ENABLED)
27.02 15:50:33 [Server] INFO Border 2.1.0 (ENABLED)
27.02 15:50:33 [Server] INFO BSkyBlock 1.14.3 (ENABLED)
27.02 15:50:33 [Server] INFO CaveBlock 1.14.2 (ENABLED)
27.02 15:50:33 [Server] INFO Challenges 0.8.3 (ENABLED)
27.02 15:50:33 [Server] INFO Chat 1.1.2 (ENABLED)
27.02 15:50:33 [Server] INFO ControlPanel 1.7.0 (ENABLED)
27.02 15:50:33 [Server] INFO DimensionalTrees 1.6.0 (ENABLED)
27.02 15:50:33 [Server] INFO ExtraMobs 1.11.0.3 (ENABLED)
27.02 15:50:33 [Server] INFO Greenhouses 1.5.0 (ENABLED)
27.02 15:50:33 [Server] INFO IslandFly 1.8.0 (ENABLED)
27.02 15:50:33 [Server] INFO Level 2.5.1 (ENABLED)
27.02 15:50:33 [Server] INFO Likes 2.0.0 (ENABLED)
27.02 15:50:33 [Server] INFO Limits 1.15.4 (ENABLED)
27.02 15:50:33 [Server] INFO MagicCobblestoneGenerator 2.2.1 (ENABLED)
27.02 15:50:33 [Server] INFO MagicSummon 1.5.0.0 (ENABLED)
27.02 15:50:33 [Server] INFO SkyGrid 1.14.1 (ENABLED)
27.02 15:50:33 [Server] INFO TwerkingForTrees 1.4.1 (ENABLED)
27.02 15:50:33 [Server] INFO VoidPortals 1.5.0.0 (ENABLED)
27.02 15:50:33 [Server] INFO Warps 1.10.2 (ENABLED)
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
There are 3 main reasons why mobs may not be able to spawn:

1. Because of BentoBox
2. Because of server/world settings
3. Because of another plugin

**BentoBox Check**
To check why your player cannot spawn a mob, even with a spawn egg, do `/obadmin why [player name]`. Then try and use the spawn egg. You will see text pop up in the console that will explain why you can use the egg, or why not. Reply with what you see.

If the text indicates that BentoBox is not blocking it, then it's the server or world settings or another plugin.

**Another Plugin**
Are you using WorldGuard? Check for world guard regions or remove WorldGuard - BentoBox doesn't need it
Do you have MultiVerse? Maybe the world is set to PEACEFUL?
Share your plugin list (do `/plugins`)

**Server**
1. What is the coordinate of your one block? If it is 0,0, then maybe it is being protected by default world spawn protection. You can change that to 0 in `server.properties` (`spawn-protection=0`), or, just leave an island at 0,0 and call it spawn.
2. Stop server. Delete spigot.yml and bukkit.yml and restart see if anything changes with the generated one.
3. Maybe /gamerule doMobSpawning true can help?
