### ISSUE TITLE
A new placeholder for prestige or a global destroyed bloc count

### ISSUE THREAD

**Issue by iSeitan** [BentoBoxWorld/AOneBlock#199]
### Is your feature request related to a problem?

Yes, when the player do a full cycle the placeholder for the count of brocken bloc reset to 0

### Describe the solution you'd like.

A new placeholder that would count the number of time the player do the full cycle OR create a placeholder for the global number of broken block in all of the cycle accomplished

### Describe alternatives you've considered.

A new placeholder that would count the number of time the player do the full cycle OR create a placeholder for the global number of broken block in all of the cycle accomplished

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Thank you for the oneblock addon, its great! :)

**Comment by RustyDagger** [comment]
Duplicate issue
#118 
&
#195 
the funny part is you already made 195 please stop spamming and lying about checking for the same issue you just make your self look stupid. people tend to ignore people that are stupid.

**Comment by iSeitan** [comment]
> Duplicate issue
> #118
> &
> #195
> the funny part is you already made 195 please stop spamming and lying about checking for the same issue you just make your self look stupid. people tend to ignore people that are stupid.

Oh yes I’m making myself look stupid for making a suggestion after reporting an issue 😂

195 and 199 is two different suggestion. Don’t insult me.

**Comment by RustyDagger** [comment]
This issue is an exact copy of 118. a total blocks broken placeholder... both the exact the same and i fail to see how 195 is not just asking for the exact same thing the fact it resets back to 0 at the end of the last phase is not a bug its intended. and you asked for a placeholder there.. for prestige or total blocks broken again.... its the same thing ima just stop before i lose any more brain cells interacting with this much stupid.
