### ISSUE TITLE
The block won't respawn

### ISSUE THREAD

**Issue by DrakMC** [BentoBoxWorld/AOneBlock#238]
### Expected behavior

The block should always respawn.

### Observed/Actual behavior

The main block in AOneBlock sometimes disappear. It happens randomly.

### Steps/models to reproduce

https://user-images.githubusercontent.com/40771376/152443183-de4b3583-cc97-4eef-b918-4ce1cb72ca77.mov

### BentoBox version

Running on Invalid (PUFFERFISH) 1.17.1.
Version of BentoBox: 1.19.0
Database: JSON
Loaded game worlds:
oneblock_world (OneBlock): World, Nether*
Loaded addons:
AOneBlock 1.9.0 (ENABLED)
Biomes 1.14.0 (ENABLED)
Challenges 0.8.4 (ENABLED)
Chat 1.1.4 (ENABLED)
Level 2.9.0 (ENABLED)
Warps 1.11.2 (ENABLED)

**Comment by tastybento** [comment]
There may be a block in the phase list that your server doesn't know how to generate. I'm not aware of Pufferfish, so I cannot test.

**Comment by DrakMC** [comment]
You can download here: https://ci.pufferfish.host/job/Pufferfish-1.17/

**Comment by BONNe** [comment]
This can happen in 3 situations:
- block break is not passed correctly: plugins may overwrite and cancel block-breaking to do it in their way. If an event is canceled, AOneBlock cannot detect that block was broken, cuz not spawn a new one.
- block spawning task was canceled by the server due to the lag - some server engines cancel some non-priority tasks if the server lags for a bit. Like spigot engine is infamous in the tech community because it cancels response signals on lag.
- network desync from client and server - block actually is replaced, but the client did not receive information about it. Similar to the ghost blocks. Rare but possible.

I added a new command: `respawnblock`. This command will respawn a magic block if it does not exist. Not much more we can do.
