### ISSUE TITLE
Blueprints don't work

### ISSUE THREAD

**Issue by Razorxd1993** [BentoBoxWorld/AOneBlock#252]
### Expected behavior

-

### Observed/Actual behavior

As soon as I insert a blueprint, whether via config.yml or ingame via the command, oneblock no longer works. (It is about nether and end islands, standard oneblock world should remain normal).

If you then enter /ob reset, you will be signed out but the oneblock is not reseted
So an empty island without owner - if you then enter /ob you have a new oneblock, this consists of bedrock and the oneblock starts only when you have destroyed the bedrock. (Then the actual oneblock appears)

If you set the blueprints back to normal (bedrock), everything works fine.

How can this be fixed ?
I only want custom islands for the nether and the end, the normal oneblock world should be standard.

(When I switch to the nether or end world, the blueprints are not inserted). 

Configs for nether and endisland are set to true.

### Steps/models to reproduce

-

### BentoBox version

1.20

### Plugin list

-

**Comment by BONNe** [comment]
Can you share your blueprints and blueprint bundles you tried to use?

**Comment by Razorxd1993** [comment]
I had first changed only the default
I have created a new bundle, there it is unfortunately exactly the same problem

I have the OneBlock config still with attached

[blueprints + config.zip](https://github.com/BentoBoxWorld/AOneBlock/files/8669999/blueprints.%2B.config.zip)

**Comment by BONNe** [comment]
Ok, I see that the building message is not right, as it does not include nether and end islands. 

Also, your blueprints are pretty enormouse, as they coppied each air block. So the pasting is slow, and that is the reason why you are not teleprted and even if you manually teleport to your island, it is just a bedrock block. 

The reason why it is just a bedrock and player is not teleported to his island, is because nether and end blueprints are not finished to be pasted.

You could remove air block copy-ing from the blueprint and save them without air blocks, or also you could increase pasting speed in bentobox/config.yml

**Comment by Razorxd1993** [comment]
Thank you very much :)

works fine now :)

one last question only: is there a maximum limit for the phases or can I write e.g. phases with 20000 or 30000 blocks ? (I mean all phases together, not individually)

kind regards

**Comment by BONNe** [comment]
There are no limits.
