### ISSUE TITLE
Leave One Block Island

### ISSUE THREAD

**Issue by auhustgammel** [BentoBoxWorld/AOneBlock#291]
### Is your feature request related to a problem?

i'd like to have some kind of way to leave the oneblock island and get back to the survival world/spawn area i didnt find any way to do this

### Describe the solution you'd like.

i think the best solution would be some kind of /ob leave command

### Describe alternatives you've considered.

i tried typing /ob and tried every command suggestion but none of them brought me out of the island

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
This is usually something provided by another plugin like a hub or lobby one, or you can set up portals for it. In other words, it's really out of scope for this plugin because different admins could want totally different things. So, I recommend you try and find another plugin to get what you need.
