### ISSUE TITLE
A new placeholder that will list each block contained in a phase.

### ISSUE THREAD

**Issue by spookymgmt** [BentoBoxWorld/AOneBlock#385]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Something like [block-phase-list], that is used in the /ob phases menu.

When used, it'll list every block contained in each phase, inside the lore of that phase in /ob phases.

Example lore when using placeholder

&7- &eCobblestone
&7- &eStone
&7- &eDirt

### Describe alternatives you've considered.

Cant think of any

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Ill throw a $30 bounty on this feature request.

**Comment by Mithranduil** [comment]
just write it self, so its not to spammy with big phases:
https://prnt.sc/-v8B1xlK3mte

**Comment by tastybento** [comment]
Please see https://github.com/BentoBoxWorld/AOneBlock/pull/386 for details on how this works and the options. It should be available for testing on ci.bentobox.world after it compiles.

**Comment by BONNe** [comment]
tasty, not that kinda of placeholder :D 

Placeholder in locale and panels

**Comment by tastybento** [comment]
Aha, okay. It would need this still though right? @spookymgmt Can you clarify?

**Comment by spookymgmt** [comment]
> Aha, okay. It would need this still though right? @spookymgmt Can you clarify?

Yes the currently added thing, thank you by the way, that is very helpful. I'll be using that. 

Also though as BONNe said, if possible could we also get one for this spot? This way, players can type /is phases, and hover over every available phase so they can see what each phase offers block wise? 

`  gui:
    titles:
      phases: '&6&lONEBLOCK &8✦ &8Phases'
    buttons:
      previous:
        name: '&f&l Previous Page'
        description: '&7 Switch to [number] page'
      next:
        name: '&f&l Next Page'
        description: '&7 Switch to [number] page'
      phase:
        name: '&f&l [phase]'
        description: "[starting-block]\n&7 \n[biome]"
        starting-block: '&7Unlocked after &e%aoneblock_my_island_count%/[number] &7blocks
          mined.'
        biome: '&7 Biome: &e [biome]'
        bank: '&7 Requires &e $[number] &7 in bank account.'
        economy: '&7 Requires &e $[number] &7 in player account.'
        level: '&7 Requires &e [number] &7 island level.'
        permission: '&7 Requires `&e[permission]&7` permission.'`


Also, I've went ahead and set the $30, thanks for looking into this.

**Comment by tastybento** [comment]
Okay, done (again!)

There are new locale strings.

[blocks] is in the description.

```
      phase:
        name: '&f&l [phase]'
        description: |-
          [starting-block]
          [biome]
          [bank]
          [economy]
          [level]
          [permission]
          [blocks]
```

Then this part defines what you'll get in [blocks]:
```
        # Replaces text with [blocks]
        blocks-prefix: '&7 Blocks in phase - '
        blocks: '&e [name], '
        wrap-at: '50'
```

Hopefully, this is self explanatory. For the wrap-at, as there can be a lot of blocks, and they are not in a long list because this is what it looked like originally:
<img width="851" alt="Screenshot 2024-04-17 at 7 52 38 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/61a6dcb4-2705-4ee3-a59b-eba014fd2054">

So, I made the formatting list it one one line with wrap done at 50 chars, so now it looks like this:

<img width="852" alt="Screenshot 2024-04-17 at 9 13 03 PM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/24bfdf4e-013e-47a1-93b6-0bb2080806e3">

Which is still a lot of text, but at least it fits. You can adjust the wrap and how each block type is formatted.

**Comment by tastybento** [comment]
Also, thanks for donation. If you are on Discord share your tag and I'll give you the donor rank.
