### ISSUE TITLE
Passing phases with a minion

### ISSUE THREAD

**Issue by Jimaie72** [BentoBoxWorld/AOneBlock#389]
### Is your feature request related to a problem?

Hello, when a minion finishes a phase, the oneblock disappears. 
The player is forced to issue the /ob respawnblock command.

Minion from : 
https://www.spigotmc.org/resources/jetsminions-1-minions-plugin-actions-upgrades-animations-robots-1-8-1-20.59972/

### Describe the solution you'd like.

I want the phase to pass automatically without placing the command

### Describe alternatives you've considered.

I want the phase to pass automatically without placing the command

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Huh, weird. This was fixed a while ago, so it sounds like a regression. I'll have to investigate.

https://github.com/BentoBoxWorld/AOneBlock/issues/300

**Comment by Jimaie72** [comment]
Update ?

**Comment by tastybento** [comment]
I was stuck debugging because it's a premium plugin and I don't have it, but I managed to fake a minion and I found a bug when a minion finishes a phase. I expect that if you look in your logs you'll find an error reported when the phase finished - this was why the block was not regenerating. Anyway, please try the latest build on ci.bentobox.world and hopefully that should work correctly. Note that minions cannot get past a phase if you have set any restrictions, e.g., permission, bank balance, etc.
