### ISSUE TITLE
Placeholder: <Player>'s island phase, block, etc.

### ISSUE THREAD

**Issue by Projecki** [BentoBoxWorld/AOneBlock#74]
**Description**

Placeholders for specific player's island phase and block, self explanatory

**Placeholder**: `__________`

%oneblock_<player>_island_phase%

**Comment by Projecki** [comment]
%oneblock_USERNAME_island_phase%

**Comment by Poslovitch** [comment]
The "username" part will require this https://github.com/BentoBoxWorld/BentoBox/issues/1070 to be done upfront.

**Comment by tastybento** [comment]
Please see https://bentobox-world.readthedocs.io/en/latest/gamemodes/AOneBlock/Placeholders/

Let me know is something is missing.

**Comment by Projecki** [comment]
I am aware that placeholders exist for your own oneblock island and the island you are visiting, but I meant for my suggestion to be a placeholder that has a specific player's island's block or phase. The purpose of this would be so I may add it on each player's chat prefix or hover text using another plugin.

**Comment by tastybento** [comment]
Okay, so you mean that `%oneblock_tastybento_island_phase%` would give you my island phase?

**Comment by Projecki** [comment]
Exactly!

**Comment by tastybento** [comment]
Okay, let me double check the use case because I'm a bit confused. You wrote:

>The purpose of this would be so I may add it on each player's chat prefix or hover text using another plugin.

If you used `%aoneblock_my_island_phase%` in the chat prefix, then when a player chatted it would look something like this:

`<tastybento>[Plains]: Hi there`

`<poslovitch>[Ocean]: What's up?`

Where the phases shown in chat are those player's phases. How would `%oneblock_tastybento_island_phase%` or `%oneblock_poslovitch_island_phase%` be used and what would chat show? Wouldn't it just be the same?

**Comment by Projecki** [comment]
I see, got it working in game. Thanks.
